// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfileSvr.Database;

#nullable disable

namespace ProfileSvr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826084506_AddKycStatusAndBankAccounts")]
    partial class AddKycStatusAndBankAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProfileSvr.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("device_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("profile_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ProfileId", "CreatedAtUtc");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("ProfileSvr.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("device_identifier");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("OsName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("os_name");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("platform");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("ProfileSvr.Domain.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("channel");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("profile_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("purpose");

                    b.Property<string>("RetrievalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("retrieval_code");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("source_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RetrievalCode")
                        .IsUnique();

                    b.HasIndex("ProfileId", "Channel");

                    b.HasIndex("Target", "Purpose");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("ProfileSvr.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<string>("Bvn")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("bvn");

                    b.Property<bool>("BvnIsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("bvn_is_verified");

                    b.Property<string>("CadAccount")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cad_account");

                    b.Property<string>("Cif")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cif");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeviceChangedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("device_changed_at_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("device_id");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email_address");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("gender");

                    b.Property<bool>("HasSetTransactionPin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("has_set_transaction_pin");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasDefaultValue("NotStarted")
                        .HasColumnName("kyc_status");

                    b.Property<string>("KycStatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("kyc_status_reason");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("NairaAccount")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naira_account");

                    b.Property<string>("Nin")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("nin");

                    b.Property<bool>("NinIsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("nin_is_verified");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("AuthCreated")
                        .HasColumnName("status");

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tier");

                    b.Property<string>("TransactionPinHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("transaction_pin_hash");

                    b.Property<string>("TransactionPinSalt")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("transaction_pin_salt");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("ProfileSvr.Domain.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("linked_at_utc");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("profile_id");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("released_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ReleasedAtUtc");

                    b.HasIndex("ProfileId", "ReleasedAtUtc");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("ProfileSvr.Domain.Activity", b =>
                {
                    b.HasOne("ProfileSvr.Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProfileSvr.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileSvr.Domain.OtpCode", b =>
                {
                    b.HasOne("ProfileSvr.Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProfileSvr.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileSvr.Domain.Profile", b =>
                {
                    b.HasOne("ProfileSvr.Domain.Device", "Device")
                        .WithMany("Profiles")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ProfileSvr.Domain.UserDevice", b =>
                {
                    b.HasOne("ProfileSvr.Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfileSvr.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileSvr.Domain.Device", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
